<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>0.1.2</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
</Project>
