<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ReportDiff.Core/ReportDiff.Core.csproj" />
    <ProjectReference Include="../../src/ReportDiff.Pdf/ReportDiff.Pdf.csproj" />
    <ProjectReference Include="../../src/ReportDiff.Report/ReportDiff.Report.csproj" />
    <ProjectReference Include="../../src/ReportDiff.Cli/ReportDiff.Cli.csproj" />
  </ItemGroup>
</Project>
