<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win.slim" Version="4.13.0.20260627" />
    <PackageReference Include="ReportDiff.OpenCvSharp4.runtime.osx" Version="4.13.0.20260627"
                      Condition="$([MSBuild]::IsOSPlatform('OSX'))" />
  </ItemGroup>
</Project>
